### ISSUE TITLE
refig.readSync is not a function

### ISSUE THREAD

**Issue by seanc** [soundcove/app-server#2]
I'm assuming some API changes were made to refig and weren't reflected here.

**EDIT**
Went ahead and switch to rc

**Comment by jamen** [comment]
Yeah...  I think I broke semver principles with refig and released breaking changes under a minor or patch maybe.

I think we should ultimately switch to something better, as I don't even really use refig anymore because there are even more simplistic libraries.  Maybe something like [`rc`](https://npmjs.com/rc)?
